services:
  - type: web
    name: malik-xgo-backend
    runtime: node
    repo: https://github.com/Huzefa0786-hack/Malik.XGO.git
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true